---
- name: getenforce check
  command: getenforce
  register: sestatus
  changed_when: false

# Download and install EPEL for Centos/RHEL version 7
- name: Download EPEL Repo - Centos/RHEL 7
  get_url: url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
           dest=/tmp/epel-release-latest-7.noarch.rpm
  when: ansible_os_family == 'RedHat'
        and ansible_distribution_major_version == '7'
        and "{{ sestatus.stdout != 'Disabled' }}"

- name: Install EPEL Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/epel-release-latest-7.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: ansible_os_family == 'RedHat'
        and ansible_distribution_major_version == '7'
        and "{{ sestatus.stdout != 'Disabled' }}"

# install libselinux-python when SELinux enabled
- name: Install libselinux-python
  yum: name=libselinux-python
  when: "{{ sestatus.stdout.find('Disabled') == -1 }}"

- name: libselinux-python install check
  command: rpm -qa libselinux-python
  register: libselinux
  changed_when: false

- debug: msg="libselinux-python installed -> {{libselinux.stdout.find('libselinux-python')}}"
- debug: msg="selinux Disabled -> {{sestatus.stdout.find('Disabled')}}"

- name: prepare check
  fail: msg="selinux not disabled OR libselinux-python not installed."
  when: "{{ sestatus.stdout.find('Disabled') == -1 }}
        and {{ libselinux.stdout.find('libselinux-python') == -1 }}"

